/* I have two document here in this file, you can create multiple documents as you want, just separated them using --- */
/* the first document defines the kubernates server, the server will allow us to access multi nodes on the single port */
kind: Service
apiVersion: v1
metadata:
  name: train-schedule-service
spec:
  type: NodePort
  selector:
    app: train-schedule
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8080

---
/* defines the deployment, tells the kubernates how to deploy the application */
/* we want two relicas(ports) that the training schedule app is running and we also specify the what contiainer to deploy. */
apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-deployment
  labels:
    app: train-schedule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
